project:
  type: website

website:
  title: "De.KCD - Data Management Platform on the Cloud - Quickstart"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
     - icon: github
       href: https://github.com/abecam/DeKCD-DMOnTheCloud

  sidebar:
    style : "docked"
    search: true
    contents:
        - index.qmd
        - pages/TechPlatformDecisionTree.qmd
        - section: "Data Management Principles"
          contents:
            - pages/DM_planning.qmd
            - pages/Pseudonymization.qmd
        - section: "Kubernetes"
          contents:
            - pages/Kubernetes_introduction.qmd
            - pages/Data_storage.qmd
            - pages/Backups_and_security.qmd
        - section: "Scrap pages"
          contents:
            - roadblocks.qmd
            - to_investigate.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



